#
# GitLab CI Script
# Builds, Tests and Deploys the {{cookiecutter.project}} {{cookiecutter.name}}
#

#
# Services
#

#
# Constant Variables
#

variables:
  DOCKER_IMAGE: {{cookiecutter.image}}
  SRC: src/{{cookiecutter.pkg}}

#
# Stages
#

stages:
  - test

#
# Common tasks to run for all stages
#

before_script:
  - export VERSION=$(head -n 1 VERSION | tr -d "\n")

#
# Test Stages
#

# Runs tests in a go image
test:
  stage: test
  image: golang:{{cookiecutter.go}}-alpine
  script:
    - apk update && apk add make build-base git
    - mkdir -p $GOPATH/$(echo $SRC | rev | cut -d'/' -f2- | rev) # mk src directory tree minus last path
    - ln -s $CI_PROJECT_DIR $GOPATH/$SRC; cd $GOPATH/$SRC
    - make test
