#
# GitLab CI Script
# Builds, Tests and Deploys the {{cookiecutter.project}} {{cookiecutter.name}}
#

#
# Services
#

#
# Constant Variables
#

variables:
  DOCKER_IMAGE: {{cookiecutter.image}}

#
# Stages
#

stages:
  - test

#
# Common tasks to run for all stages
#

before_script:
  - export VERSION=$(head -n 1 VERSION | tr -d "\n")

#
# Test Stages
#

# Runs tests in a go image
test:
  stage: test
  image: golang:{{cookiecutter.go}}-alpine
  script:
    - apk update && apk add make build-base git
    - make test
