#
# GitLab CI Configuration
#

# Environment Variables
variables:
  IMAGE: {{ cookiecutter.docker_image_name }}
  SRC: src/{{ cookiecutter.project_name|lower }}

# Build Stages
stages:
  - test
  - release

# Builds and Tests the Application
test_job:
  stage: test
  image: golang:1.6.2-alpine
  artifacts:
    paths:
      - .build/
  script:
    - apk update && apk add ca-certificates openssl openssh make git bash
    - wget -qO- https://github.com/kardianos/govendor/releases/download/v1.0.3/govendor_linux_386 > $GOPATH/bin/govendor
    - chmod +x $GOPATH/bin/govendor
    - mkdir -p $GOPATH/src
    - ln -s $CI_PROJECT_DIR $GOPATH/$SRC
    - cd $GOPATH/$SRC
    - TEST_VERBOSE=1 make test build_linux64

# Release Job
release_job:
  stage: release
  only:
    - master
  script:
    - apt-get update && apt-get install make
    - DOCKER_TAG=$CI_BUILD_REF make image
    - docker login --username=$DOCKER_USER --password=$DOCKER_PASS $DOCKER_REGISTRY
    - docker tag $IMAGE:${CI_BUILD_REF} $IMAGE:latest
    - docker push $IMAGE:latest
    - docker push $IMAGE:${CI_BUILD_REF}
